config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  resources :vendors, controller: 'vendors'
  get "/sell" => "vendors#new"
  get "/shops" => "vendors#index"
  get "/about" => "about#index"
  resources :messages, controller: 'messages'
  get "/contact" => "messages#new"
  get "/coming" => "coming#index"
  resources :subscriptions
end

app/models/message.rb
class Message < ApplicationRecord
    validates :name, presence: true
    validates :notification_email, presence: true#, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :subject, presence: true
    validates :body, presence: true
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/subscription.rb
class Spree::Subscription < ApplicationRecord
    validates :name, presence: true
    validates :notification_email, presence: true, uniqueness: true
end

app/controllers/spree/about_controller.rb
class Spree::AboutController < ApplicationController
    include Spree::Core::ControllerHelpers::Store
    include Spree::Core::ControllerHelpers::Common
    include Spree::Core::ControllerHelpers::Currency
    helper Spree::BaseHelper

    def index

    end
end

app/controllers/spree/coming_controller.rb
class Spree::ComingController < ApplicationController
  include Spree::Core::ControllerHelpers::Store
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::Currency
  helper Spree::BaseHelper
  
  def index
    @subscription = Spree::Subscription.new
  end
end

app/controllers/spree/messages_controller.rb
class Spree::MessagesController < ApplicationController
    include Spree::Core::ControllerHelpers::Store
    include Spree::Core::ControllerHelpers::Common
    include Spree::Core::ControllerHelpers::Currency
    helper Spree::BaseHelper
    invisible_captcha only: [:create], honeypot: :subtitle, on_spam: :spam_callback_method

    def index

    end

    def new
      @message = Message.new
    end

    def create
        @message = Message.new(message_params)
    
        if @message.save
          flash[:success] = Spree.t('message.message_sent')
          redirect_back fallback_location: root_path
        else 
          flash[:error] = Spree.t('message.message_not_sent')
          render :new
        end
    end

    private
    def message_params
      params.require(:message).permit(:name, :notification_email, :subject, :body, :newsletter)
    end

    def spam_callback_method
      redirect_to root_path
    end
end

app/controllers/spree/subscriptions_controller.rb
class Spree::SubscriptionsController < ApplicationController
  include Spree::Core::ControllerHelpers::Store
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::Currency
  helper Spree::BaseHelper

  def index
  end
  
  def new
    @subscription = Spree::Subscription.new
  end

  def create
      @subscription = Spree::Subscription.new(subscription_params)
  
      if @subscription.save
        flash[:success] = Spree.t('message.message_sent')
        redirect_back fallback_location: root_path
      else 
        flash[:error] = Spree.t('message.message_not_sent')
        render :new
      end
  end

  private
  def subscription_params
    params.require(:subscription).permit(:name, :notification_email)
  end
end

app/controllers/spree/vendors_controller.rb
class Spree::VendorsController < ApplicationController
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::Store
  include Spree::Admin::VendorHelper
  include Spree::Core::ControllerHelpers::Currency
  helper Spree::BaseHelper
  helper Spree::ProductsHelper

  rescue_from ActiveRecord::RecordNotFound, with: :resource_not_found
  rescue_from ActiveRecord::RecordNotUnique, with: :record_not_unique
  
  def index
    #the shops page will only list active sellers
    @vendors = Spree::Vendor.active.all
  end

  def show
    #@vendor = Spree::Vendor.find(params[:id])
    @vendor = Spree::Vendor.friendly.find(params[:id])
    @products = @vendor.products

    #set a taxon in order to avoid the display of products.jpg in spree/products/index
    @taxon = Spree::Taxon.find_by_name('Buy')
  end

  def new
    if try_spree_current_user
      if current_spree_vendor
        case current_spree_vendor.state
          when 'active' then redirect_to admin_path #redirects to the admin page
          when 'pending' then flash[:warning] = Spree.t('seller.seller_request_pending')
            redirect_to vendor_path(current_spree_vendor) #redirects to the seller details page
          when 'blocked' then flash[:warning] = Spree.t('seller.seller_request_blocked')
            redirect_to vendor_path(current_spree_vendor) #redirects to the seller details page
        end
      else
        @vendor = Spree::Vendor.new
        #email text field will be pre-filled with current user's email address
        @vendor.notification_email = current_spree_user.email
      end
    else
      store_location #sets session return url
      flash[:warning] = Spree.t('seller.user_account')
      redirect_to create_new_session_path #redirects to login page
    end
  end

  def create
    #all attributes except image is attached to the vendor model
    @vendor = Spree::Vendor.new(vendor_params.except(:image))

    #all attributes (input text from the form) except the image are saved in the database
    #@vendor.attributes = vendor_params.except(:image)

    #image is attached to the vendor model
    if vendor_params[:image] && Spree.version.to_f >= 3.6
      @vendor.build_image(attachment: vendor_params[:image])
    end

    respond_to do |format|
      if @vendor.save
        map_vendor
        flash[:success] = Spree.t('seller.seller_request_submitted')
        format.html { redirect_to vendor_path(current_spree_vendor) }
        format.js { render layout: false }
      else
        format.html { render :new }
        format.js { render layout: false }
      end
    end
  end

  private

  def vendor_params
    #params.require(:vendor).permit(:name, :about_us, :contact_us, :image)
    params.require(:vendor).permit(Spree::PermittedAttributes.vendor_attributes)
  end

  def map_vendor
    #mapping the spree user with the seller
    current_spree_user.vendors << @vendor
  end

  def resource_not_found
    flash[:error] = Spree.t('seller.resource_not_found')
    redirect_to root_path
  end

  #This method catches the ActiveRecord::RecordNotUnique exception. The exception is thrown when a record already exists in the database but marked as deleted.
  def record_not_unique
    #An additional error message is added to the vendor model if the seller name already exists as part of a record marked as deleted. 
    @vendor.errors.add(:name, :not_unique, message: Spree.t('seller.name_taken'))
    render :new
  end
end

app/helpers/spree/coming_helper.rb
module Spree::ComingHelper
end

app/helpers/spree/messages_helper.rb
module Spree::MessagesHelper
end

app/helpers/spree/subscriptions_helper.rb
module Spree::SubscriptionsHelper
end

app/views/spree/about/index.html.erb
<% self.title = Spree.t('about.about_us') %>
<div class="d-flex justify-content-center mb-5">
	<div class="panel panel-default">
		<div>
			<%= image_tag "/images/banner.png", class: "responsive" %>
		</div>
		<div id="intro" class="container-fluid text-center text-padding bg-sand">
			<h1><%= Spree.t('about.intro_title') %></h1>			
			<p><%= Spree.t('about.intro_subtitle') %></p>
			<br/>
			<br/>
			<br/>
			<div>
				<h5>Check out our DEMO site here:</h5>
				<h5><%= link_to "demo.torgobi.com", root_path %></h5>
			</div>
		</div>
		<!-- Container (About Section) -->
		<div id="about" class="container-fluid text-center text-padding">
			<h2><%= Spree.t('about.about_us') %></h2>
			<br>
			<h5><%= Spree.t('about.about_us_text') %></h5>
			<br>
			<br>
			<%= link_to Spree.t('message.get_in_touch'), contact_path, class: 'btn btn-primary spree-btn' %>
		</div>
		<!-- Container (How It Works Section) -->
		<div id="services" class="container-fluid text-center text-padding bg-sand">
			<h2><%= Spree.t('about.services_title') %></h2>
			<br>
			<h5><%= Spree.t('about.services_text') %>:</h5>
			<br>
			<div class="row">
				<div class="col-sm-3">
					<%= image_tag "/images/globe.png" %>
					<span class="glyphicon glyphicon-globe logo-small"></span>
					<h4><%= Spree.t('about.services_step1_title') %></h4>
					<p><%= Spree.t('about.services_step1_text') %></p>
				</div>
				<div class="col-sm-3">
					<%= image_tag "/images/buy.png" %>
					<span class="glyphicon glyphicon-shopping-cart logo-small"></span>
					<h4><%= Spree.t('about.services_step2_title') %></h4>
					<p><%= Spree.t('about.services_step2_text') %></p>
				</div>
				<div class="col-sm-3">
					<%= image_tag "/images/location.png" %>
					<span class="glyphicon glyphicon-map-marker logo-small"></span>
					<h4><%= Spree.t('about.services_step3_title') %></h4>
					<p><%= Spree.t('about.services_step3_text') %></p>
				</div>
				<div class="col-sm-3">
					<%= image_tag "/images/plane.png" %>
					<span class="glyphicon glyphicon-send logo-small"></span>
					<h4><%= Spree.t('about.services_step4_title') %></h4>
					<p><%= Spree.t('about.services_step4_text') %></p>
				</div>				
			</div>
		</div>
		<!-- Container (Team Section) -->
		<div id="team" class="container-fluid text-center text-padding">
			<h2><%= Spree.t('about.team_title') %></h2>
			<br>
			<h5><%= Spree.t('about.team_text') %>:</h5>
			<br>
			<div class="row text-center">
				<div class="col-sm-3">
					<div>						
						<%= image_tag "/images/bil.png" %>
						<p><strong>Bilguun</strong></p>
						<p><%= Spree.t('about.team_member1') %></p>
					</div>
				</div>
				<div class="col-sm-3">
					<div>
						<%= image_tag "/images/dim.png" %>
						<p><strong>Dima</strong></p>
						<p><%= Spree.t('about.team_member2') %></p>
					</div>
				</div>
				<div class="col-sm-3">
					<div>
						<%= image_tag "/images/zuz.png" %>
						<p><strong>Zuzana</strong></p>
						<p><%= Spree.t('about.team_member3') %></p>
					</div>
				</div>
				<div class="col-sm-3">
					<div>
						<%= image_tag "/images/gun.png" %>
						<p><strong>Gunnar</strong></p>
						<p><%= Spree.t('about.team_member4') %></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/spree/coming/index.html.erb
<% self.title = Spree.t('coming.coming_soon') %>
<div class="container d-flex justify-content-center mb-5">
  <div class="col-md-6">
    <div class="panel panel-default">
      <h1 class="cs-headline"><%= Spree.t('coming.coming_soon') %></h1>
      <%= render "spree/shared/subscription" %>
    </div>
  </div>
</div>

app/views/spree/messages/new.html.erb
<% self.title = Spree.t('message.contact_us') %>
<div class="container d-flex justify-content-center mb-5">
<div class="col-md-6">
<div class="panel panel-default">
  <h3 class="spree-mb-large spree-mt-large spree-header"><%= Spree.t('message.contact_us') %></h3>
  <div id="message" class="panel-body" data-hook="login">
  <%= form_with model: @message, url: messages_path, local: true do |f| %>
    <div class="mb-4">
      <%= f.invisible_captcha :subtitle, visual_honeypots: false %>
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.text_field :name, class: 'spree-flat-input', placeholder: Spree.t('message.name'), autofocus: true, required: true %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @message, param: :name} %>
      </div>
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.email_field :notification_email, class: 'spree-flat-input', placeholder: Spree.t('message.email'), autofocus: true, required: true %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @message, param: :notification_email} %>
      </div>
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.text_field :subject, class: 'spree-flat-input', placeholder: Spree.t('message.subject'), autofocus: true, required: true %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @message, param: :subject} %>
      </div>
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.text_area :body, class: 'spree-flat-input', placeholder: Spree.t('message.body'), autofocus: true, required: true %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @message, param: :body} %>
      </div>
      <div class="spree-checkbox-container mt-4 mt-sm-5 mt-lg-4 spree-mb-medium">
        <div class="spree-checkbox">
          <%= f.check_box :newsletter, { checked: true } %>
          <%= f.label :newsletter, '' %>
        </div>
        <%= f.label :newsletter, Spree.t('message.subscribe'), class: 'spree-checkbox-label' %>
      </div>
    </div>
    <div>
      <%= f.submit Spree.t('message.send'), class: "btn btn-primary btn-block spree-btn mt-2 mb-3", data: { disable_with: "#{ Spree.t('seller.sending') }" } %>
    </div>
    <div>
      <!-- <%= render 'spree/shared/error_messages', target: @vendor %> -->
    </div>
  <% end %>
  </div>
</div>
</div>
</div>

app/views/spree/shared/_error_message.html.erb
<% if target && target.errors.full_messages_for(param).any? %>
  <div id="errorExplanation" class="alert alert-danger d-flex justify-content-center mb-0" data-hook>
     <ul class="mb-0 pl-0"  style="list-style-type: none;">
        <% target.errors.full_messages_for(param).each do |message| %>
          <li><%= message %></li>
        <% end %>
     </ul>
     <br/>
  </div>
<% end %>

app/views/spree/shared/_subscription.html.erb
  <h5 class="spree-mb-medium spree-mt-medium spree-header"><%= Spree.t('coming.get_notified') %></h5>
  <div id="subscription" class="panel-body" data-hook="login">
  <%= form_with model: @subscription, url: subscriptions_path, local: true do |f| %>
    <div class="mb-4">
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.text_field :name, class: 'spree-flat-input', placeholder: Spree.t('message.name'), autofocus: true, required: true %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @subscription, param: :name} %>
      </div>
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.email_field :notification_email, class: 'spree-flat-input', placeholder: Spree.t('message.email'), autofocus: true, required: true %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @subscription, param: :notification_email} %>
      </div>
    </div>
    <div>
      <%= f.submit Spree.t('coming.subscribe'), class: "btn btn-primary btn-block spree-btn mt-2 mb-3", data: { disable_with: "#{ Spree.t('seller.sending') }" } %>
    </div>
  <% end %>
  </div>

app/views/spree/subscriptions/new.html.erb
<div class="container d-flex justify-content-center mb-5">
<div class="col-md-6">
<div class="panel panel-default">
  <h5 class="spree-mb-medium spree-mt-medium spree-header"><%= Spree.t('coming.get_notified') %></h5>
  <div id="subscription" class="panel-body" data-hook="login">
  <%= form_with model: @subscription, url: subscriptions_path, local: true do |f| %>
    <div class="mb-4">
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.text_field :name, class: 'spree-flat-input', placeholder: Spree.t('message.name'), autofocus: true, required: true %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @subscription, param: :name} %>
      </div>
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.email_field :notification_email, class: 'spree-flat-input', placeholder: Spree.t('message.email'), autofocus: true, required: true %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @subscription, param: :notification_email} %>
      </div>
    </div>
    <div>
      <%= f.submit Spree.t('coming.subscribe'), class: "btn btn-primary btn-block spree-btn mt-2 mb-3", data: { disable_with: "#{ Spree.t('seller.sending') }" } %>
    </div>
  <% end %>
  </div>
</div>
</div>
</div>

app/views/spree/vendors/index.html.erb
<% self.title = Spree.t('seller.shops') %>
<h1 class="spree-mb-large spree-mt-large spree-header"><%= Spree.t('seller.shops') %></h1>
<div class="container-fluid">
  <% @vendors.each do |vendor| %>
    <div class="d-none d-md-block mt-4 mb-5 pb-5 vendors-list-item">
      <h4 class="text-uppercase text-center mb-4"> <%= vendor.name %> </h4>
      <div class="row">
        <div class="col-12 col-md-3 vendors-list-item-image">
          <%= image_tag main_app.url_for(vendor.image.url(:large)) if vendor.image %>
        </div>
        <div class="col-12 col-md-6">
          <div class="vendors-list-item-about">
            <%= vendor.about_us %>
          </div>
        </div>
        <div class="col-12 col-md-3 d-flex flex-column align-items-center justify-content-center">
          <div class="vendors-list-item-btn">
            <%= link_to Spree.t('seller.shop_now'), vendor, class: "btn btn-primary spree-btn px-5 w-75" %>
          </div>
        </div>
      </div>
    </div>
    <div class="d-md-none vendors-list-item--mobile">
      <button
        class="p-0 btn w-100"
        type="button"
        data-toggle="collapse"
        data-target="#vendor-description-<%= vendor.id %>"
        aria-expanded="false"
        aria-controls="vendor-description-<%= vendor.id %>"
      >
        <h4 class="text-left my-2"><%= vendor.name %></h4>
      </button>
      <div class="collapse" id="vendor-description-<%= vendor.id %>">
        <div>
          <div class="vendors-list-item-image">
            <%= image_tag main_app.url_for(vendor.image.url(:small)) if vendor.image %>
          </div>
          <div class="my-4">
            <%= vendor.about_us %>
          </div>
          <div class="mb-4 d-flex justify-content-end">
            <div class="vendors-list-item--mobile">
              <%= link_to Spree.t('seller.shop_now'), vendor, class: "btn btn-primary spree-btn w-100" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %> 
</div>

app/views/spree/vendors/new.html.erb
<% self.title = Spree.t('seller.seller_signup') %>
<div class="container d-flex justify-content-center mb-5">
<div class="col-md-6">
<div class="panel panel-default">
  <h3 class="spree-mb-large spree-mt-large spree-header"><%= Spree.t('seller.request_seller_account') %></h3>
  <div id="new-vendor" class="panel-body" data-hook="login">
  <%= form_with model: @vendor, url: vendors_path, local: true do |f| %>
    <div class="mb-4">
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.text_field :name, class: 'spree-flat-input', placeholder: Spree.t('seller.seller_name'), autofocus: true, required: true %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @vendor, param: :name} %>
      </div>
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.text_area :about_us, class: 'spree-flat-input', placeholder: Spree.t('seller.about_us'), autofocus: true, required: true %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @vendor, param: :about_us} %>
      </div>
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.text_area :contact_us, class: 'spree-flat-input', placeholder: Spree.t('seller.address'), autofocus: true, required: true %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @vendor, param: :contact_us} %>
      </div>
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.label :image, Spree.t('seller.image'), class: 'spree-flat-label' %>
          <%= f.file_field :image, accept: 'image/png,image/jpeg,image/jpg,image/gif', class: 'spree-flat-input' %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @vendor, param: :image} %>
      </div>
      <div class="form-group mb-4">
        <p class="form-group checkout-content-inner-field">
          <%= f.text_field :notification_email, class: 'spree-flat-input', placeholder: Spree.t('seller.email'), autofocus: true, required: true %>
        </p>
        <%= render partial: "spree/shared/error_message", locals: {target: @vendor, param: :notification_email} %>
      </div>
    </div>
    <div>
      <%= f.submit Spree.t('seller.send_request'), class: "btn btn-primary btn-block spree-btn mt-2 mb-3", data: { disable_with: "#{ Spree.t('seller.sending') }" } %>
    </div>
    <div>
      <!-- <%= render 'spree/shared/error_messages', target: @vendor %> -->
    </div>
  <% end %>
  </div>
</div>
</div>
</div>

app/views/spree/vendors/show.html.erb
<div class="container">
    <div class="row px-lg-3 vendor-details">
        <div class="col-12 text-uppercase text-center mt-4 mb-5 mb-sm-4">
            <h1 class="mt-2 mb-4"><%= @vendor.name %></h1>
            <h5 class="mt-2 mb-4"><%= @vendor.state %></h5>
        </div>
        <div class="col-12 col-sm-6 col-lg-5 text-center pt-sm-4 pt-lg-3 vendor-details-image">
            <%= image_tag main_app.url_for(@vendor.image.url(:large)) if @vendor.image %>
        </div>
        <div class="col-12 col-sm-6 col-lg-5 offset-lg-1 mt-5 mt-sm-0 vendor-description">
            <div class="vendor-details-about">
                <p class="mb-0"><%= @vendor.about_us %></p>
            </div>
        </div>
    </div>
    <div data-hook="taxon_products">
        <%= render template: 'spree/products/index' %>
    </div>
</div>